const fs = require('fs');
const { createClient } = require('@supabase/supabase-js');

const envPath = './.env.local';
if (!fs.existsSync(envPath)) {
  console.error("Error: .env.local file not found.");
  process.exit(1);
}

const envContent = fs.readFileSync(envPath, 'utf-8');
const env = {};
envContent.split('\n').forEach(line => {
  const match = line.match(/^\s*([\w.\-]+)\s*=\s*(.*)?\s*$/);
  if (match) {
    let value = match[2] || '';
    if (value.startsWith('"') && value.endsWith('"')) value = value.slice(1, -1);
    if (value.startsWith("'") && value.endsWith("'")) value = value.slice(1, -1);
    env[match[1]] = value.trim();
  }
});

const supabaseUrl = env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.error("Error: Missing Supabase credentials in .env.local");
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);
const NUM_PLAYERS = 80;
const SERVER_URL = 'http://localhost:3001/api/submit-answer';

async function runScaleTest() {
  console.log("=== Starting Scale Test ===");
  console.log(`Targeting local server at: ${SERVER_URL}`);
  console.log(`Simulating ${NUM_PLAYERS} concurrent players...`);

  // 1. Fetch an existing host
  const { data: hosts, error: hostErr } = await supabase.from('hosts').select('id').limit(1);
  if (hostErr || !hosts || hosts.length === 0) {
    console.error("Error: Could not retrieve a host from the 'hosts' table. Make sure you have signed up at least one host.", hostErr);
    process.exit(1);
  }
  const hostId = hosts[0].id;
  console.log(`Using Host ID: ${hostId}`);

  // 2. Create a temporary quiz
  console.log("Creating temporary scale test quiz...");
  const { data: quiz, error: quizErr } = await supabase.from('quizzes').insert({
    host_id: hostId,
    title: 'Scale Test Quiz (Auto)',
    description: 'Generated by scale-test script',
  }).select().single();

  if (quizErr || !quiz) {
    console.error("Error creating quiz:", quizErr);
    process.exit(1);
  }

  // 3. Create a temporary question
  console.log("Creating temporary quiz question...");
  const { data: question, error: questionErr } = await supabase.from('questions').insert({
    quiz_id: quiz.id,
    order_index: 0,
    type: 'mcq',
    prompt: 'What is 10 + 10?',
    answers: [
      { id: 'opt_1', text: '10', is_correct: false, color: '#ef4444', shape: 'triangle' },
      { id: 'opt_2', text: '20', is_correct: true, color: '#3b82f6', shape: 'diamond' }
    ]
  }).select().single();

  if (questionErr || !question) {
    console.error("Error creating question:", questionErr);
    // Cleanup
    await supabase.from('quizzes').delete().eq('id', quiz.id);
    process.exit(1);
  }

  // 4. Create a game session
  const pin = Math.floor(100000 + Math.random() * 900000).toString();
  console.log(`Creating game session with PIN: ${pin}...`);
  const { data: session, error: sessionErr } = await supabase.from('game_sessions').insert({
    quiz_id: quiz.id,
    host_id: hostId,
    pin: pin,
    status: 'question_active',
    current_question_index: 0,
    question_started_at: new Date().toISOString()
  }).select().single();

  if (sessionErr || !session) {
    console.error("Error creating session:", sessionErr);
    // Cleanup
    await supabase.from('questions').delete().eq('id', question.id);
    await supabase.from('quizzes').delete().eq('id', quiz.id);
    process.exit(1);
  }

  // 5. Create 80+ players in the database
  console.log(`Adding ${NUM_PLAYERS} players to the lobby...`);
  const playersToInsert = [];
  for (let i = 1; i <= NUM_PLAYERS; i++) {
    playersToInsert.push({
      session_id: session.id,
      nickname: `Player_${i}`,
      client_token: `token_player_${i}_${Math.random().toString(36).substr(2, 5)}`,
      connected: true,
      score: 0,
      streak: 0
    });
  }

  const { data: players, error: playersErr } = await supabase.from('players').insert(playersToInsert).select();
  if (playersErr || !players || players.length !== NUM_PLAYERS) {
    console.error("Error inserting players:", playersErr);
    // Cleanup
    await supabase.from('game_sessions').delete().eq('id', session.id);
    await supabase.from('questions').delete().eq('id', question.id);
    await supabase.from('quizzes').delete().eq('id', quiz.id);
    process.exit(1);
  }
  console.log(`Successfully added ${players.length} players!`);

  // 6. Concurrently submit answers to Next.js API Route
  console.log("Simulating concurrent player answers...");
  const latencies = [];
  let successCount = 0;
  let failCount = 0;

  const promises = players.map(async (player, index) => {
    // Add a small randomized delay (100ms - 1500ms) to simulate real human pacing
    const delay = 100 + Math.random() * 1400;
    await new Promise(resolve => setTimeout(resolve, delay));

    const startTime = Date.now();
    try {
      const response = await fetch(SERVER_URL, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          sessionId: session.id,
          playerId: player.id,
          token: player.client_token,
          questionId: question.id,
          selectedAnswerIds: ['opt_2'] // submit the correct answer
        })
      });

      const latency = Date.now() - startTime;
      latencies.push(latency);

      const resBody = await response.json();
      if (response.ok && resBody.success) {
        successCount++;
      } else {
        console.error(`Player_${index + 1} submission rejected:`, resBody.error || response.statusText);
        failCount++;
      }
    } catch (err) {
      failCount++;
      console.error(`Player_${index + 1} request error:`, err.message);
    }
  });

  const testStartTime = Date.now();
  await Promise.all(promises);
  const totalDuration = Date.now() - testStartTime;

  console.log("\n=== Scale Test Results ===");
  console.log(`Total duration: ${totalDuration}ms`);
  console.log(`Total simulated players: ${NUM_PLAYERS}`);
  console.log(`Success submissions: ${successCount}`);
  console.log(`Failed submissions: ${failCount}`);

  if (latencies.length > 0) {
    const avgLatency = latencies.reduce((a, b) => a + b, 0) / latencies.length;
    const minLatency = Math.min(...latencies);
    const maxLatency = Math.max(...latencies);
    console.log(`Average API Latency: ${avgLatency.toFixed(1)}ms`);
    console.log(`Min API Latency: ${minLatency}ms`);
    console.log(`Max API Latency: ${maxLatency}ms`);
  }

  // 7. Verify Database answers submitted count
  console.log("\nVerifying database answers submission count...");
  const { data: dbSubmissions, error: dbErr } = await supabase
    .from('answers_submitted')
    .select('*')
    .eq('session_id', session.id);

  if (dbErr) {
    console.error("Database query failed:", dbErr);
  } else {
    console.log(`Total submissions in database: ${dbSubmissions.length}`);
    if (dbSubmissions.length === NUM_PLAYERS) {
      console.log("✅ Verification Success! All submissions successfully processed and recorded.");
    } else {
      console.error(`❌ Verification Failed! Expected ${NUM_PLAYERS} entries, found ${dbSubmissions.length} entries.`);
    }
  }

  // 8. Cleanup test data
  console.log("\nCleaning up test data from the database...");
  await supabase.from('game_sessions').delete().eq('id', session.id);
  await supabase.from('questions').delete().eq('id', question.id);
  await supabase.from('quizzes').delete().eq('id', quiz.id);
  console.log("Cleanup complete!");
  console.log("=== Scale Test Finished ===");
}

runScaleTest();
